# Generated by Django 3.1.1 on 2021-05-20 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='Cartt',
        ),
        migrations.RenameModel(
            old_name='CartItem',
            new_name='CarttItem',
        ),
        migrations.AlterModelTable(
            name='carttitem',
            table='CarttItem',
        ),
    ]
